title = "Vno Hugo"
baseURL = ""
theme = "vno"
paginate = 10
paginatePath = "page"
themesDir = "themes"
publishDir = "public"

[outputs]
home = [ "HTML", "RSS" ]

[[menu.main]]
name = "Projects"
identifier = "projects"
url = "http://project.onevcat.com/"
weight = 10

[taxonomies]
tag = "tags"

[params]
author = "onevcat"
subtitle = "A blog-orientation theme for Hugo"
description = "Vno Hugo is a port of Vno Jekyll."
welcomeMessage = "Oh What a World"
coverColor = "red"

  [params.comment]
  disqus = "vno-hugo"
  duoshuo = ""

    [params.comment.gitalk]
    ID = ""
    secret = ""
    repo = ""
    owner = ""

  [params.social]
  weibo = "onevcat"
  github = "onevcat"
  twitter = "onevcat"
  gplus = "107108267983477358170"
  mail = "onev@onevcat.com"

  [params.ga]
  ID = "your_ga_id"
  host = "your_host"

  [params.blogButton]
  title = "Blog"
  description = "Visit blog"

[permalinks]
posts = "/:year/:month/:title/"
